services:
  - type: web
    name: mastercrono
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
    healthCheckPath: /
    autoDeploy: true 